#!/usr/bin/env bash
# install and configure HApoxy on lb-01 server

# First we ensure our port is not currently in use
# lsof - list our files pid status
# -i specfies the protocol port number
# -t ensures that only matching case

port_status=$(lsof -t -i :80) # since it's an arrary
for pid in $port_status
do
	sudo kill "$pid" &>/dev/null
done

# updat and install the Haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# configure the haproxy file
# we append to the existing configuration using -a
sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null <<EOF
frontend http_requests
	bind *:80
	mode http
	default_backend web_backend

backend web_backend
	mode http
	balance roundrobin
	server 120066-web-01 100.25.204.113:80 check
	server 120066-web-02 52.86.36.187:80 check
EOF

# alternatively to make the script init enaable
# configure the defualt file
# SET ENABLE=1
# Set ENABLED to 1 if you want the init script to start haproxy.
sudo tee -a /etc/default/haproxy >/dev/null <<EOF
ENABLE=1
EOF


# start haproxy
sudo service haproxy restart
