#!/usr/bin/env bash
# a fizbuzz of 1-100
num=({1..100})
for cnt in "${num[@]}"
do
	if (( cnt % 3 == 0 )) && (( cnt % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( cnt % 3 == 0 ))
	then
		echo "Fizz"
	elif (( cnt % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$cnt"
	fi
done
