#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
output=$(cat /etc/passwd)
while read -r eachline
do
	username=$(echo "$eachline" | cut -d: -f1)
	uid=$(echo "$eachline" | cut -d: -f3)
	homedir=$(echo "$eachline" | cut -d: -f6)

	# Display the required information for each user
	echo "$username:$uid:$homedir"

done <<< "$output"
