#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
output=$(cat /etc/passwd)
while IFS=: read -r username psd uid gid uid_info hdir c_shell
do
	echo "The user ${username} is part of the ${gid} gang, lives in ${hdir} and rides ${c_shell}. ${uid}'s place is protected by the passcode ${psd}, more info about the user here: ${uid_info}"

done <<< "$output"
