#!/usr/bin/env bash
# displaying "Best School" 10 times
msg="Best School"
cnt=0
while ((cnt<10))
do
        echo "$msg"
        if ((cnt==8))
        then
                echo "Hi"
        fi
        cnt=$(( cnt+1 ))
done
