#!/usr/bin/env bash
# displaying "Best School" 10 times
msg="Best School"
msg4="bad luck"
msg8="good luck"
cnt=0
while ((cnt<10))
do
        if ((cnt==3))
        then
                echo "$msg4"
        elif ((cnt==7))
        then
                echo "$msg8"
        else
                echo "$msg"
        fi
        ((cnt++))
done
