#!/usr/bin/env bash
# displaying "Best School" 10 times
msg4="bad luck from China"
msg9="bad luck from Japan"
msg17="bad luck from Italy"
cnt=1
while ((cnt<21))
do
        echo "$cnt"
        case $cnt in
                4)
                        echo "$msg4"
                        ;;
                9)
                        echo "$msg9"
                        ;;
                17)
                        echo "$msg17"
                        ;;
        esac
        ((cnt++))
done
