#!/usr/bin/env bash
# displaying "Best School" 10 times
dsp="Hour:"
hr=0
mins=1
while ((hr<13))
do
        echo "$dsp $hr"
        while((mins<60))
        do                
                echo "$mins"
                ((mins++))
        done
        mins=1
        ((hr++))
done
