#!/usr/bin/env bash
# a bash script that displays the directory in a list format
# and truncating every namae that has -
disp=( * )
for file in "${disp[@]}"
do
	if [[ $file == *-* ]]
	then
		name=${file#*-}
		echo "$name"
	else
		echo "$file"
	fi
done
