#!/usr/bin/env bash
# script that gives you information about a file.
file="school"
file_exist="school file exists"
file_nexist="school file does not exist"
file_empty="school file is empty"
file_nempty="school file is not empty"
file_regular="school is a regular file"

if [ -e "$file" ]
then
	echo "$file_exist"
	if [ -s "$file" ]
	then
		echo "$file_nempty"
	else
		echo "$file_empty"
	fi
	if [ -f "$file" ]
	then
		echo "$file_regular"
	fi
else
	echo "$file_nexist"
fi
