#!/usr/bin/env bash
# Bash script that runs the whoami command

# check if args passed is null
if [[ -z "$1" ]]
then
	echo "Usage error: <pass user>"
    	exit 1
fi

# Run the whoami command under the specified user
sudo -u "$1" whoami
